@CodeTogether.WebAPI_HostAddress = http://localhost:5236

GET {{CodeTogether.WebAPI_HostAddress}}/api/Room

###

POST {{CodeTogether.WebAPI_HostAddress}}/api/Auth/RegisterUser
Content-Type: Application/JSON

{

}
